---
title: "Uncertainty Exploration"
author: "Tyler Jubenville"
date: "6/12/2020"
output: html_document
---


```{r}
library(tidyverse) # metapackage of all tidyverse packages
library(readr) # importing data
library(forecast) # time series
library(zoo)
#library(pryr) # 
```

```{r}
## IMPORT FILES.
## Files commented out to save memory
path <- "data"
calendar <- read_csv(file.path(path,"calendar.csv"))
sales_train_evaluation <- read_csv(file.path(path, "sales_train_evaluation.csv"))
sales_train_validation <- read_csv(file.path(path, "sales_train_validation.csv"))
sample_submission <- read_csv(file.path(path, "sample_submission.csv"))
sell_prices <- read_csv(file.path(path, "sell_prices.csv"))
```

```{r}
col_tf <- colnames(sales_train_validation) %>% stringr::str_detect("d_")
vars <- colnames(sales_train_validation)[col_tf]
```

```{r}
data_creator <- function(df, ...){
  output <- df %>% group_by(...) %>% 
    summarize_at(.vars = vars,
                 .funs = c(sum="sum"))
  return(output)
}
```


```{r}
L1 <-  data_creator(sales_train_validation)
L2 <-  data_creator(sales_train_validation, state_id)
L3 <-  data_creator(sales_train_validation, store_id)
L4 <-  data_creator(sales_train_validation, cat_id)
L5 <-  data_creator(sales_train_validation, dept_id)
L6 <-  data_creator(sales_train_validation, state_id, cat_id)
L7 <-  data_creator(sales_train_validation, state_id, dept_id)
L8 <-  data_creator(sales_train_validation, store_id, cat_id)
L9 <-  data_creator(sales_train_validation, store_id, dept_id)
L10 <- data_creator(sales_train_validation, item_id)
L11 <- data_creator(sales_train_validation, item_id, state_id)
L12 <- data_creator(sales_train_validation, item_id, store_id)
data_level_list <- list(L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12)
```

```{r}
calendar <- mutate(calendar, day = str_replace(d, "d_", ""),
                   sporting_event = case_when(event_type_1 == "Sporting" | event_type_2 == "Sporting" ~ 1,
                                              TRUE ~ 0),
                   cultural_event = case_when(event_type_1 == "Cultural" | event_type_2 == "Cultural" ~ 1,
                                              TRUE ~ 0),
                   national_event = case_when(event_type_1 == "National" | event_type_2 == "National" ~ 1,
                                              TRUE ~ 0),
                   religious_event = case_when(event_type_1 == "Religious" | event_type_2 == "Religious" ~ 1,
                                              TRUE ~ 0)) %>%
  select(day, wday, date, snap_CA, snap_TX, snap_WI, sporting_event, cultural_event, national_event, religious_event)
head(calendar, 10)
```

```{r}
L1_long <- L1 %>%  
   pivot_longer(cols = starts_with("d_"),
               names_to = "day",
               names_prefix = "d_",
               values_to = "sales") %>% 
  mutate(day = str_replace(day, "_sum", ""))


head(L1_long)


ggplot(L1_long, aes(day, sales)) + geom_line()
```

```{r}
model_data <- left_join(L1_long, calendar, by = "day")
#cols <- c("item_id", "dept_id", "cat_id", "store_id", "state_id")
#L1_long <- L1_long %>%
#  mutate_at(cols, factor)

head(model_data)
```


```{r}
## LET'S DO TIME SERIES
## WORKING VERSION FOR ONE PREDICTION
simple_series <- select(model_data, sales, date)
#head(simple_series)
mod_xts <- msts(simple_series$sales, seasonal.periods = c(7,365.25))
#head(mod_xts)
autoplot(mod_xts)
fit <- tbats(mod_xts)
percentiles <- c(50, 67, 95, 99)
fc <- forecast(fit, h = 28, level = percentiles)
plot(fc)
summary(fit)
head(fc)

nums <- 1:28
paste0("F", nums)
row_labs<- paste0("F", nums)
rownames(fc$lower) <- row_labs
rownames(fc$upper) <- row_labs

res <- cbind(fc$lower[,(ncol(fc$lower)):1], fc$mean ,fc$upper[,1:(ncol(fc$upper))])

res
col_vals <- c("0.005", "0.025", "0.165", "0.250", "0.500", "0.750", "0.835", "0.975", "0.995")
fact_1 <- "Total"
fact_2 <- "X"
file <- "validation"
for (i in 1:length(col_vals)){
  col_vals[i] <- paste0(fact_1, "_", fact_2, "_", col_vals[i], "_", file)
}
colnames(res) <- col_vals

rownames(res) <- row_labs
output <- t(res)

results <- single_series_model(model_data, fact_1, fact_2, file)
head(results)
```


```{r}
single_series_model <- function(model_data, fact_1, fact_2, file){
  
  simple_series <- select(model_data, sales, date)
  
  mod_xts <- msts(simple_series$sales, seasonal.periods = c(7,365.25))
  fit <- tbats(mod_xts)
  percentiles <- c(50, 67, 95, 99)
  fc <- forecast(fit, h = 28, level = percentiles)
  #plot(fc)
  #summary(fit)
  #head(fc)
  
  nums <- 1:28
  paste0("F", nums)
  row_labs<- paste0("F", nums)
  rownames(fc$lower) <- row_labs
  rownames(fc$upper) <- row_labs
  
  res <- cbind(fc$lower[,(ncol(fc$lower)):1], fc$mean ,fc$upper[,1:(ncol(fc$upper))])
  
  #res
  
  col_vals <- c("0.005", "0.025", "0.165", "0.250", "0.500", "0.750", "0.835", "0.975", "0.995")
  
  
  for (i in 1:length(col_vals)){
    col_vals[i] <- paste0(fact_1, "_", fact_2, "_", col_vals[i], "_", file)
  }
  
  
  colnames(res) <- col_vals
  
  rownames(res) <- row_labs
  output <- t(res)
  return(output)
}
```

```{r}
model_builder <- function(base_data, calendar_data, expected_cols, file){
  
  test_val <- ncol(base_data) - expected_cols
  if(test_val == 0){
    fact_1 <- "Total"
    fact_2 <- "X"
  } else if(test_val == 1){
    fact_1 <- unlist(unique(base_data[,1]))
    fact_2 <- "X"
  } else if(test_val == 2){
    fact_1 <- unlist(unique(base_data[,1]))
    fact_2 <- unlist(unique(base_data[,2]))
  }
  
  results_list <- list()
  counter = 1
  for (i in 1:length(fact_1)){
    for (j in 1:length(fact_2)){
      
      if(test_val == 0){
        one_series <- base_data[counter,]
      } else if(test_val == 1){
        one_series <- base_data[counter,2:ncol(base_data)]
      } else if(test_val == 2){
        one_series <- base_data[counter,3:ncol(base_data)]
      }
      
      one_series_long <- one_series %>%  
        pivot_longer(cols = starts_with("d_"),
                     names_to = "day",
                     names_prefix = "d_",
                     values_to = "sales") %>% 
        mutate(day = str_replace(day, "_sum", ""))
      
      model_data <- left_join(one_series_long, calendar_data, by = "day")
      
      results_list[[counter]] <- single_series_model(model_data, fact_1[i], fact_2[j], file = file)
      
      counter = counter + 1
    }
  }
  
  final_vals <- do.call(rbind, results_list)
  
  return(final_vals)
}
```




```{r}
testL1 <- model_builder(L1, calendar, ncol(L1), "validation")
head(testL1)
testL2 <- model_builder(L2, calendar, ncol(L1), "validation")
head(testL2)
testL6 <- model_builder(L6, calendar, ncol(L1), "validation")
head(testL6)
output <- rbind(testL1, testL2, testL6) %>% as.data.frame()
write.csv(output, "output_test.csv")
```


```{r}
list_test <- list(testL1, testL2, testL6)
list_test[[1]]
length(list_test)
```


